const {test,expect}=require('@playwright/test');
test('carga la landing y el panel',async({page})=>{await page.goto('/',{waitUntil:'domcontentloaded'});await expect(page.locator('body')).toBeVisible();await page.goto('/panel/',{waitUntil:'domcontentloaded'});await expect(page.locator('#login')).toBeAttached();await expect(page).toHaveTitle(/Panel|Streaming/i)});
test('la portada se ordena en una sola columna en móvil',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');const content=page.locator('.heroGrid>div').first(),phone=page.locator('.heroGrid>.phone');await expect(content).toBeVisible();await expect(phone).toBeVisible();const [contentBox,phoneBox]=await Promise.all([content.boundingBox(),phone.boundingBox()]);expect(contentBox).not.toBeNull();expect(phoneBox).not.toBeNull();expect(phoneBox.y).toBeGreaterThanOrEqual(contentBox.y+contentBox.height-2);expect(phoneBox.x).toBeGreaterThanOrEqual(0);expect(phoneBox.x+phoneBox.width).toBeLessThanOrEqual(390)});
test('los botones del encabezado quedan centrados en móvil',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');const buttons=page.locator('.nav .actions .btn');await expect(buttons).toHaveCount(2);for(const button of await buttons.all()){await expect(button).toHaveCSS('justify-content','center');await expect(button).toHaveCSS('align-items','center');const box=await button.boundingBox();expect(box.height).toBeGreaterThanOrEqual(54)}});
test('la opción activa mantiene contraste en modo oscuro',async({page})=>{await page.goto('/panel/');await page.evaluate(()=>document.documentElement.setAttribute('data-theme','dark'));const active=page.locator('.side-menu .tab.active').first();await expect(active).toBeAttached();const colors=await active.evaluate(el=>{const s=getComputedStyle(el);return{background:s.backgroundColor,color:s.color}});expect(colors.background).not.toBe('rgba(0, 0, 0, 0)');expect(colors.background).not.toBe(colors.color)});
test('incluye el módulo profesional de inventario',async({page})=>{await page.goto('/panel/');await expect(page.locator('[data-tab="inventory"]')).toBeAttached();await expect(page.locator('#inventory')).toBeAttached();await expect(page.locator('#inventoryModal')).toBeAttached();await expect(page.locator('#inventoryMovementModal')).toBeAttached()});
test('incluye cocina y caja sin el antiguo monitor',async({page})=>{await page.goto('/panel/');await expect(page.locator('[data-tab="kitchen"]')).toBeAttached();await expect(page.locator('[data-tab="cash"]')).toBeAttached();await expect(page.locator('#kitchenBoard')).toBeAttached();await expect(page.locator('#cashOpenPanel')).toBeAttached();await expect(page.locator('[data-tab="health"]')).toHaveCount(0)});
test('incluye POS, personal e historial de caja',async({page})=>{await page.goto('/panel/');await expect(page.locator('[data-tab="pos"]')).toBeAttached();await expect(page.locator('#posProductList')).toBeAttached();await expect(page.locator('#posCartList')).toBeAttached();await expect(page.locator('[data-tab="staff"]')).toBeAttached();await expect(page.locator('#staffList')).toBeAttached();await expect(page.locator('#cashHistoryList')).toBeAttached()});
test('incluye acciones para pagos de suscripción pendientes',async({page})=>{await page.goto('/panel/');await expect(page.locator('#subscriptionPaymentHistory')).toBeAttached();const source=await page.content();expect(source).toContain('managePendingSubscriptionPayment');expect(source).toContain('Continuar pago')});
test('oculta el contador de suscripción solo dentro de Plan y facturación',async({page})=>{await page.goto('/panel/');await page.evaluate(()=>{document.body.classList.remove('auth-loading');document.body.classList.add('auth-ready');document.querySelector('#app').classList.remove('hidden');currentRole='restaurant';restaurants=[{id:1,name:'Demo',subscription_status:'trial',subscription_plan:'Prueba',subscription_expires_at:new Date(Date.now()+86400000).toISOString()}];currentRestaurant=1;document.querySelectorAll('.section').forEach(x=>x.classList.remove('active'));document.querySelector('#plans').classList.add('active');syncSubscriptionBannerForActiveTab()});await expect(page.locator('#subscriptionBanner')).toBeHidden();await page.evaluate(()=>{document.querySelector('#plans').classList.remove('active');document.querySelector('#dashboard').classList.add('active');syncSubscriptionBannerForActiveTab()});await expect(page.locator('#subscriptionBanner')).toBeVisible()});
test('incluye centro de plan y facturación',async({page})=>{await page.goto('/panel/');await expect(page.locator('[data-tab="plans"]')).toBeAttached();await expect(page.locator('#billingCurrentPlan')).toBeAttached();await expect(page.locator('#billingPaymentMethods')).toBeAttached();await expect(page.locator('#restaurantPlans')).toBeAttached();await expect(page.locator('#subscriptionPaymentHistory')).toBeAttached();await expect(page.locator('#plans')).toContainText(/Plan y Facturación/i)});
test('incluye promociones y reseñas administradas por el restaurante',async({page})=>{await page.goto('/panel/');await expect(page.locator('[data-tab="promotions"]')).toBeAttached();await expect(page.locator('[data-tab="reviews"]')).toBeAttached();await expect(page.locator('#promotions')).toBeAttached();await expect(page.locator('#reviews')).toBeAttached();await expect(page.locator('#restaurantPromotionModal')).toBeAttached();await expect(page.locator('#restaurantReviewResponseModal')).toBeAttached()});
test('pedidos permanece oculto cuando está activo el dashboard móvil',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/panel/');await expect(page.locator('#dashboard')).toHaveCSS('display','block');await expect(page.locator('#orders')).toHaveCSS('display','none')});
test('no contiene la integración experimental de WhatsApp',async({page})=>{await page.goto('/panel/');await expect(page.locator('[data-tab="whatsapp-demo"]')).toHaveCount(0);await expect(page.locator('#whatsapp-demo')).toHaveCount(0);await expect(page.locator('footer')).toContainText(/Versión v2\.(?:4|5)\.\d+/)});
test('el mesero ve solamente Meseros POS',async({page})=>{await page.goto('/panel/');await page.evaluate(()=>{document.body.classList.remove('auth-loading');document.body.classList.add('auth-ready');document.querySelector('#app').classList.remove('hidden');currentRole='waiter';applyRoleAccess()});await expect(page.locator('.side-menu .tab:not([hidden])')).toHaveCount(1);await expect(page.locator('.side-menu .tab[data-tab="pos"]')).toBeVisible();await expect(page.locator('.side-menu .tab[data-tab="dashboard"]')).toBeHidden();await expect(page.locator('#viewMenuLink')).toBeHidden();await expect(page.locator('#pos')).toHaveClass(/active/)});
test('cocina ve solamente su pantalla',async({page})=>{await page.goto('/panel/');await page.evaluate(()=>{document.body.classList.remove('auth-loading');document.body.classList.add('auth-ready');document.querySelector('#app').classList.remove('hidden');currentRole='kitchen';applyRoleAccess()});await expect(page.locator('.side-menu .tab:not([hidden])')).toHaveCount(1);await expect(page.locator('.side-menu .tab[data-tab="kitchen"]')).toBeVisible();await expect(page.locator('.side-menu .tab[data-tab="staff"]')).toBeHidden();await expect(page.locator('#kitchen')).toHaveClass(/active/)});
test('incluye gestión de tamaños y extras por producto',async({page})=>{await page.goto('/panel/');await expect(page.locator('#optionsModal')).toBeAttached();await expect(page.locator('#optionGroupType')).toBeAttached();await expect(page.locator('#optionGroupsList')).toBeAttached()});
test('las acciones del panel son compactas en móvil',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/panel/');const menu=page.locator('#sideMenuToggle');await expect(menu).toBeAttached();await expect(menu.locator('.action-label')).toHaveCSS('display','none');await expect(menu).toHaveCSS('width','40px');await expect(page.locator('#themeBtn')).toHaveAttribute('aria-label',/modo/i)});
test('al elegir una sección se cierra el menú y su fondo',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/panel/');await page.evaluate(()=>{toggleSideMenu();document.querySelector('.tab[data-tab="products"]').click()});await expect(page.locator('#sideMenu')).not.toHaveClass(/open/);await expect(page.locator('#sideMenuBackdrop')).not.toHaveClass(/open/)});
test('login de restaurante con cuenta de prueba',async({page})=>{test.skip(!process.env.RESTAURANT_TEST_EMAIL||!process.env.RESTAURANT_TEST_PASSWORD,'Credenciales de prueba no configuradas');await page.goto('/panel/');await page.locator('#email').fill(process.env.RESTAURANT_TEST_EMAIL);await page.locator('#password').fill(process.env.RESTAURANT_TEST_PASSWORD);await page.getByRole('button',{name:/Ingresar/i}).click();await expect(page.locator('#app')).toBeVisible({timeout:15000})});

test('incluye Flow Chile en Plan y facturación',async({page})=>{await page.goto('/panel/');const html=await page.content();expect(html).toContain('paySubscriptionPlanFlow');expect(html).toContain('create-flow-subscription-payment');expect(html).toContain('subscription-flow-settings')});

test('reconcilia suscripciones de Mercado Pago al cargar facturación',async({page})=>{await page.goto('/panel/');const html=await page.content();expect(html).toContain('syncMercadoPagoSubscription');expect(html).toContain('sync-mercadopago-subscription')});

test('incluye suscripción automática y cancelación pendiente con Flow',async({page})=>{await page.goto('/panel/');const html=await page.content();expect(html).toContain('payFlowRecurringSubscription');expect(html).toContain('Suscribirme con Flow');expect(html).toContain('manageFlowPendingPayment');expect(html).toContain('create-flow-recurring-subscription');expect(html).toContain('manage-flow-pending-payment')});

test('incluye gestión de suscripciones recurrentes',async({page})=>{await page.goto('/panel/');const html=await page.content();expect(html).toContain('manageRecurringSubscription');expect(html).toContain('Cancelar suscripción Flow');expect(html).toContain('Pausar renovación Mercado Pago');expect(html).toContain('Reactivar suscripción Mercado Pago');expect(html).toContain('cancel-recurring-subscription')});

test('incluye modal profesional para comprar planes',async({page})=>{await page.goto('/panel/');const html=await page.content();expect(html).toContain('planCheckoutModal');expect(html).toContain('openPlanPurchaseModal');expect(html).toContain('Pagar con Mercado Pago');expect(html).toContain('Pagar con Flow');expect(html).toContain('Reactivar con Mercado Pago')});

test('mantiene módulos permitidos juntos sin huecos',async({page})=>{await page.goto('/panel/');const html=await page.content();expect(html).toContain('syncSidebarGroupVisibility');expect(html).toContain('grid-auto-rows:max-content');expect(html).toContain('align-content:start')});

test('no renderiza el contador dentro de Plan y facturación',async({page})=>{await page.goto('/panel/');const html=await page.content();expect(html).toContain('subscriptionBannerShouldShow');expect(html).toContain('activeTab!=="plans"');expect(html).toContain('banner.innerHTML=""')});

test('usa la misma escala visual del menú admin',async({page})=>{await page.goto('/panel/');const html=await page.content();expect(html).toContain('restaurant-admin-sidebar-scale-v2464');expect(html).toContain('font-size:15px!important;font-weight:720!important');expect(html).toContain('width:44px!important;height:44px!important')});

test('panel restaurante cerrado copia referencia admin sin barra visible',async({page})=>{await page.goto('/panel/');const html=await page.content();expect(html).toContain('restaurant-collapsed-admin-reference-v2465');expect(html).toContain('scrollbar-width:none');expect(html).toContain('width:62px!important')});

test('restringe POS y Cocina por rol y exige caja abierta',async({page})=>{await page.goto('/panel/');const html=await page.content();expect(html).toContain('operationalTabLockReason');expect(html).toContain('restaurant_has_open_cash');expect(html).toContain('posCashGate');expect(html).toContain('usuario con rol Mesero');expect(html).toContain('usuario con rol Cocina')});

test('permite elegir mensual o anual en la compra del plan',async({page})=>{await page.goto('/panel/');const html=await page.content();expect(html).toContain('planCheckoutCycleAnnual');expect(html).toContain('setPlanPurchaseCycle');expect(html).toContain('billing_cycle:billingCycle');expect(html).toContain('12 meses de acceso')});


test('panel abre menú demo con sesión administrativa temporal', async ({ request }) => {
  const response=await request.get('/panel/');
  expect(response.ok()).toBeTruthy();
  const body=await response.text();
  expect(body).toContain('openMenuFromPanel');
  expect(body).toContain('admin_client_token_hash');
  expect(body).toContain('create-admin-preview-login');
});
