/* YummyPro Streaming · núcleo operativo v0.2.0 */
let streamingPlatforms=[];
let streamingCustomers=[];
let streamingAccounts=[];
let streamingSubscriptions=[];
let streamingRenewals=[];
let streamingSubscriptionView="all";
let streamingSubscriptionSearch="";
let streamingModalSaveHandler=null;

function streamingEsc(value){return String(value??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function streamingToast(message){try{return toast(message)}catch(_){console.log(message)}}
function streamingLocale(){try{return currentRestaurantConfig?.locale||"es-CL"}catch(_){return "es-CL"}}
function streamingCurrency(){try{return currentRestaurantConfig?.currency_code||"CLP"}catch(_){return "CLP"}}
function streamingMoney(value,currency=streamingCurrency()){try{return new Intl.NumberFormat(streamingLocale(),{style:"currency",currency,maximumFractionDigits:0}).format(Number(value||0))}catch(_){return `${currency} ${Number(value||0).toLocaleString()}`}}
function streamingDate(value,withTime=false){if(!value)return "—";const d=new Date(value);if(Number.isNaN(d.getTime()))return "—";return d.toLocaleString(streamingLocale(),withTime?{dateStyle:"medium",timeStyle:"short"}:{dateStyle:"medium"})}
function streamingDateInput(value){const d=value?new Date(value):new Date();if(Number.isNaN(d.getTime()))return "";const z=n=>String(n).padStart(2,"0");return `${d.getFullYear()}-${z(d.getMonth()+1)}-${z(d.getDate())}T${z(d.getHours())}:${z(d.getMinutes())}`}
function streamingDaysLeft(value){const t=new Date(value).getTime();if(!Number.isFinite(t))return null;return Math.ceil((t-Date.now())/86400000)}
function streamingDerivedStatus(row){if(row.status==="cancelled")return "cancelled";if(row.status==="paused")return "paused";return new Date(row.expires_at).getTime()<=Date.now()?"expired":"active"}
function streamingStatusLabel(row){const st=streamingDerivedStatus(row),days=streamingDaysLeft(row.expires_at);if(st==="expired")return "Vencida";if(st==="cancelled")return "Cancelada";if(st==="paused")return "Pausada";if(days!=null&&days<=7)return `Vence en ${Math.max(0,days)} día${days===1?"":"s"}`;return "Activa"}
function streamingStatusClass(row){const st=streamingDerivedStatus(row),days=streamingDaysLeft(row.expires_at);return st==="expired"||st==="cancelled"?"streaming-badge danger":st==="paused"?"streaming-badge muted":days!=null&&days<=7?"streaming-badge warning":"streaming-badge good"}
function streamingWritable(){try{if(currentBusinessIsDemo()){streamingToast("La demostración es de solo lectura. Crea tu cuenta para guardar cambios.");return false}}catch(_){}return true}
function streamingPlatform(id){return streamingPlatforms.find(x=>Number(x.id)===Number(id))}
function streamingCustomer(id){return streamingCustomers.find(x=>Number(x.id)===Number(id))}
function streamingAccount(id){return streamingAccounts.find(x=>Number(x.id)===Number(id))}
function streamingSubscription(id){return streamingSubscriptions.find(x=>Number(x.id)===Number(id))}

function installStreamingUi(){
 if(document.getElementById("streaming_subscriptions"))return;
 const css=document.createElement("link");css.rel="stylesheet";css.href="/panel/streaming.css?v=0200";document.head.appendChild(css);
 const tabs=document.querySelector("#sideMenu .tabs");
 if(tabs){
  const management=[...tabs.querySelectorAll(".nav-group-label")].find(x=>x.textContent.trim()==="GESTIÓN");
  const holder=document.createElement("div");
  holder.innerHTML=`<div class="nav-group-label streaming-nav-label">STREAMING</div>
  <button class="tab streaming-tab" data-tab="streaming_subscriptions" title="Suscripciones"><span class="nav-icon">◫</span><span class="nav-label">Suscripciones</span></button>
  <button class="tab streaming-tab" data-tab="streaming_customers" title="Clientes"><span class="nav-icon">◎</span><span class="nav-label">Clientes</span></button>
  <button class="tab streaming-tab" data-tab="streaming_accounts" title="Cuentas y cupos"><span class="nav-icon">▣</span><span class="nav-label">Cuentas / Cupos</span></button>
  <button class="tab streaming-tab" data-tab="streaming_platforms" title="Plataformas"><span class="nav-icon">▶</span><span class="nav-label">Plataformas</span></button>
  <button class="tab streaming-tab" data-tab="streaming_renewals" title="Renovaciones"><span class="nav-icon">↻</span><span class="nav-label">Renovaciones</span></button>`;
  const nodes=[...holder.children];nodes.forEach(n=>management?tabs.insertBefore(n,management):tabs.appendChild(n));
 }
 const orders=document.getElementById("orders");
 if(orders){
  const shell=document.createElement("div");
  shell.innerHTML=`
<section id="streaming_subscriptions" class="section"><div class="card streaming-shell"><div class="streaming-head"><div><span class="eyebrow">CONTROL DE VENCIMIENTOS</span><h2>Suscripciones de clientes</h2><p class="mut">Controla quién tiene acceso, en qué cuenta está, cuándo vence y cuándo renovar.</p></div><button class="primary" type="button" onclick="streamingOpenSubscription()">＋ Nueva suscripción</button></div><div class="streaming-kpis"><article><span>Activas</span><b id="streamingActiveCount">0</b></article><article><span>Vencen en 7 días</span><b id="streamingExpiringCount">0</b></article><article><span>Vencidas</span><b id="streamingExpiredCount">0</b></article><article><span>Cupos libres</span><b id="streamingFreeSlotsCount">0</b></article></div><div class="streaming-toolbar"><input id="streamingSubscriptionSearch" type="search" placeholder="Buscar cliente, plataforma o cuenta" oninput="streamingSubscriptionSearch=this.value;renderStreamingSubscriptions()"><div class="streaming-filters"><button class="ghost active" data-streaming-filter="all" onclick="setStreamingSubscriptionView('all',this)">Todas</button><button class="ghost" data-streaming-filter="active" onclick="setStreamingSubscriptionView('active',this)">Activas</button><button class="ghost" data-streaming-filter="expiring" onclick="setStreamingSubscriptionView('expiring',this)">Por vencer</button><button class="ghost" data-streaming-filter="expired" onclick="setStreamingSubscriptionView('expired',this)">Vencidas</button></div><button class="ghost" type="button" onclick="loadStreamingSubscriptions()">↻ Actualizar</button></div><div id="streamingSubscriptionList" class="streaming-list"></div></div></section>
<section id="streaming_customers" class="section"><div class="card streaming-shell"><div class="streaming-head"><div><span class="eyebrow">CLIENTES</span><h2>Directorio de clientes</h2><p class="mut">Datos de contacto y sus suscripciones activas o vencidas.</p></div><button class="primary" type="button" onclick="streamingOpenCustomer()">＋ Nuevo cliente</button></div><div class="streaming-toolbar"><input id="streamingCustomerSearch" type="search" placeholder="Buscar por nombre, teléfono o correo" oninput="renderStreamingCustomers(this.value)"><button class="ghost" onclick="loadStreamingCustomers()">↻ Actualizar</button></div><div id="streamingCustomerList" class="streaming-list"></div></div></section>
<section id="streaming_accounts" class="section"><div class="card streaming-shell"><div class="streaming-head"><div><span class="eyebrow">INVENTARIO DIGITAL</span><h2>Cuentas y cupos</h2><p class="mut">Administra las cuentas disponibles y cuántos perfiles puede usar cada una. YummyPro no guarda contraseñas.</p></div><button class="primary" type="button" onclick="streamingOpenAccount()">＋ Nueva cuenta</button></div><div class="streaming-toolbar"><input id="streamingAccountSearch" type="search" placeholder="Buscar cuenta o plataforma" oninput="renderStreamingAccounts(this.value)"><button class="ghost" onclick="loadStreamingAccounts()">↻ Actualizar</button></div><div id="streamingAccountList" class="streaming-list"></div></div></section>
<section id="streaming_platforms" class="section"><div class="card streaming-shell"><div class="streaming-head"><div><span class="eyebrow">CATÁLOGO</span><h2>Plataformas</h2><p class="mut">Define Netflix, Disney+, Spotify u otras plataformas y su duración predeterminada.</p></div><button class="primary" type="button" onclick="streamingOpenPlatform()">＋ Nueva plataforma</button></div><div id="streamingPlatformList" class="streaming-list"></div></div></section>
<section id="streaming_renewals" class="section"><div class="card streaming-shell"><div class="streaming-head"><div><span class="eyebrow">HISTORIAL</span><h2>Renovaciones</h2><p class="mut">Cada extensión de servicio queda registrada con fecha anterior, nueva fecha y forma de pago.</p></div><button class="ghost" onclick="loadStreamingRenewals()">↻ Actualizar</button></div><div id="streamingRenewalList" class="streaming-list"></div></div></section>`;
  [...shell.children].forEach(n=>orders.before(n));
 }
 if(!document.getElementById("streamingModal")){
  const modal=document.createElement("dialog");modal.id="streamingModal";modal.className="streaming-dialog";modal.innerHTML=`<div class="streaming-dialog-head"><div><span class="eyebrow">YUMMYPRO STREAMING</span><h2 id="streamingModalTitle">Editar</h2></div><button class="ghost" type="button" onclick="streamingCloseModal()">✕</button></div><div id="streamingModalBody"></div><div class="streaming-dialog-actions"><button class="ghost" type="button" onclick="streamingCloseModal()">Cancelar</button><button id="streamingModalSave" class="primary" type="button">Guardar</button></div>`;document.body.appendChild(modal);
  modal.querySelector("#streamingModalSave").addEventListener("click",async()=>{if(streamingModalSaveHandler)await streamingModalSaveHandler()});
  modal.addEventListener("click",e=>{if(e.target===modal)streamingCloseModal()});
 }
}
installStreamingUi();

function streamingShowModal(title,body,handler){const d=document.getElementById("streamingModal");if(!d)return;document.getElementById("streamingModalTitle").textContent=title;document.getElementById("streamingModalBody").innerHTML=body;streamingModalSaveHandler=handler;d.showModal?.()}
function streamingCloseModal(){streamingModalSaveHandler=null;document.getElementById("streamingModal")?.close?.()}

async function streamingFetchAll(){
 if(!currentRestaurant)return;
 const requests=[
  sb.from("streaming_platforms").select("*").eq("restaurant_id",currentRestaurant).order("sort_order").order("name"),
  sb.from("streaming_customers").select("*").eq("restaurant_id",currentRestaurant).order("full_name"),
  sb.from("streaming_accounts").select("*").eq("restaurant_id",currentRestaurant).order("active",{ascending:false}).order("label"),
  sb.from("streaming_subscriptions").select("*").eq("restaurant_id",currentRestaurant).order("expires_at",{ascending:true}),
  sb.from("streaming_renewals").select("*").eq("restaurant_id",currentRestaurant).order("created_at",{ascending:false}).limit(500)
 ];
 const result=await Promise.all(requests);const err=result.find(x=>x.error)?.error;if(err)throw err;
 [streamingPlatforms,streamingCustomers,streamingAccounts,streamingSubscriptions,streamingRenewals]=result.map(x=>x.data||[]);
}
async function loadStreamingSubscriptions(){try{await streamingFetchAll();renderStreamingSubscriptions();renderStreamingAccounts();}catch(e){console.error(e);streamingToast(e.message||"No se pudieron cargar las suscripciones")}}
async function loadStreamingCustomers(){try{await streamingFetchAll();renderStreamingCustomers(document.getElementById("streamingCustomerSearch")?.value||"")}catch(e){console.error(e);streamingToast(e.message||"No se pudieron cargar los clientes")}}
async function loadStreamingAccounts(){try{await streamingFetchAll();renderStreamingAccounts(document.getElementById("streamingAccountSearch")?.value||"")}catch(e){console.error(e);streamingToast(e.message||"No se pudieron cargar las cuentas")}}
async function loadStreamingPlatforms(){try{await streamingFetchAll();renderStreamingPlatforms()}catch(e){console.error(e);streamingToast(e.message||"No se pudieron cargar las plataformas")}}
async function loadStreamingRenewals(){try{await streamingFetchAll();renderStreamingRenewals()}catch(e){console.error(e);streamingToast(e.message||"No se pudieron cargar las renovaciones")}}

function streamingAccountUsed(id){const now=Date.now();return streamingSubscriptions.filter(s=>Number(s.account_id)===Number(id)&&s.status==="active"&&new Date(s.starts_at).getTime()<=now&&new Date(s.expires_at).getTime()>now).length}
function streamingFreeSlots(){return streamingAccounts.filter(a=>a.active).reduce((n,a)=>n+Math.max(0,Number(a.max_slots||1)-streamingAccountUsed(a.id)),0)}
function setStreamingSubscriptionView(view,btn){streamingSubscriptionView=view;document.querySelectorAll("[data-streaming-filter]").forEach(x=>x.classList.toggle("active",x===btn));renderStreamingSubscriptions()}
function renderStreamingSubscriptions(){
 const root=document.getElementById("streamingSubscriptionList");if(!root)return;
 const q=String(streamingSubscriptionSearch||document.getElementById("streamingSubscriptionSearch")?.value||"").trim().toLowerCase();
 const active=streamingSubscriptions.filter(s=>streamingDerivedStatus(s)==="active"),expiring=active.filter(s=>{const d=streamingDaysLeft(s.expires_at);return d!=null&&d>=0&&d<=7}),expired=streamingSubscriptions.filter(s=>streamingDerivedStatus(s)==="expired");
 const set=(id,v)=>{const el=document.getElementById(id);if(el)el.textContent=String(v)};set("streamingActiveCount",active.length);set("streamingExpiringCount",expiring.length);set("streamingExpiredCount",expired.length);set("streamingFreeSlotsCount",streamingFreeSlots());
 let rows=streamingSubscriptions.filter(s=>{const st=streamingDerivedStatus(s),d=streamingDaysLeft(s.expires_at);if(streamingSubscriptionView==="active"&&st!=="active")return false;if(streamingSubscriptionView==="expiring"&&!(st==="active"&&d!=null&&d>=0&&d<=7))return false;if(streamingSubscriptionView==="expired"&&st!=="expired")return false;const c=streamingCustomer(s.customer_id),p=streamingPlatform(s.platform_id),a=streamingAccount(s.account_id);return !q||[c?.full_name,c?.phone,p?.name,a?.label,s.profile_label].some(v=>String(v||"").toLowerCase().includes(q))});
 rows.sort((a,b)=>new Date(a.expires_at)-new Date(b.expires_at));
 root.innerHTML=rows.map(s=>{const c=streamingCustomer(s.customer_id)||{},p=streamingPlatform(s.platform_id)||{},a=streamingAccount(s.account_id),days=streamingDaysLeft(s.expires_at);return `<article class="streaming-row"><div class="streaming-row-main"><div class="streaming-row-title"><b>${streamingEsc(c.full_name||"Cliente")}</b><span class="${streamingStatusClass(s)}">${streamingEsc(streamingStatusLabel(s))}</span></div><div class="streaming-row-meta"><span>▶ ${streamingEsc(p.name||"Plataforma")}</span>${a?`<span>▣ ${streamingEsc(a.label)}</span>`:""}${s.profile_label?`<span>Perfil: ${streamingEsc(s.profile_label)}</span>`:""}</div><div class="streaming-dates"><span>Inicio <b>${streamingDate(s.starts_at)}</b></span><span>Vence <b>${streamingDate(s.expires_at)}</b></span>${days!=null?`<span>${days<0?`${Math.abs(days)} días vencida`:days===0?"Vence hoy":`${days} días restantes`}</span>`:""}</div></div><div class="streaming-row-actions"><button class="ghost" type="button" onclick="streamingOpenWhatsApp(${s.id})">WhatsApp</button><button class="ghost" type="button" onclick="streamingOpenSubscription(${s.id})">Editar</button><button class="primary" type="button" onclick="streamingOpenRenewal(${s.id})">Renovar</button></div></article>`}).join("")||'<div class="streaming-empty">No hay suscripciones que coincidan con este filtro.</div>';
}
function renderStreamingCustomers(search=""){
 const root=document.getElementById("streamingCustomerList");if(!root)return;const q=String(search||"").trim().toLowerCase();const rows=streamingCustomers.filter(c=>!q||[c.full_name,c.phone,c.email].some(v=>String(v||"").toLowerCase().includes(q)));
 root.innerHTML=rows.map(c=>{const subs=streamingSubscriptions.filter(s=>Number(s.customer_id)===Number(c.id)),active=subs.filter(s=>streamingDerivedStatus(s)==="active").length;return `<article class="streaming-row"><div class="streaming-row-main"><div class="streaming-row-title"><b>${streamingEsc(c.full_name)}</b>${c.active?'<span class="streaming-badge good">Activo</span>':'<span class="streaming-badge muted">Inactivo</span>'}</div><div class="streaming-row-meta">${c.phone?`<span>☎ ${streamingEsc(c.phone)}</span>`:""}${c.email?`<span>✉ ${streamingEsc(c.email)}</span>`:""}<span>${active} activa${active===1?"":"s"} · ${subs.length} total</span></div></div><div class="streaming-row-actions">${c.phone?`<button class="ghost" onclick="streamingCustomerWhatsApp(${c.id})">WhatsApp</button>`:""}<button class="ghost" onclick="streamingOpenCustomer(${c.id})">Editar</button><button class="primary" onclick="streamingOpenSubscription(null,${c.id})">Asignar</button></div></article>`}).join("")||'<div class="streaming-empty">Todavía no registraste clientes.</div>';
}
function renderStreamingAccounts(search=""){
 const root=document.getElementById("streamingAccountList");if(!root)return;const q=String(search||"").trim().toLowerCase();const rows=streamingAccounts.filter(a=>{const p=streamingPlatform(a.platform_id);return !q||[a.label,a.login_identifier,p?.name].some(v=>String(v||"").toLowerCase().includes(q))});
 root.innerHTML=rows.map(a=>{const p=streamingPlatform(a.platform_id),used=streamingAccountUsed(a.id),max=Number(a.max_slots||1),free=Math.max(0,max-used);return `<article class="streaming-row"><div class="streaming-row-main"><div class="streaming-row-title"><b>${streamingEsc(a.label)}</b>${a.active?`<span class="streaming-badge ${free?"good":"warning"}">${free} de ${max} libres</span>`:'<span class="streaming-badge muted">Desactivada</span>'}</div><div class="streaming-row-meta"><span>▶ ${streamingEsc(p?.name||"Sin plataforma")}</span>${a.login_identifier?`<span>Login: ${streamingEsc(a.login_identifier)}</span>`:""}<span>${used} en uso</span></div></div><div class="streaming-row-actions"><button class="ghost" onclick="streamingOpenAccount(${a.id})">Editar</button></div></article>`}).join("")||'<div class="streaming-empty">Todavía no registraste cuentas.</div>';
}
function renderStreamingPlatforms(){const root=document.getElementById("streamingPlatformList");if(!root)return;root.innerHTML=streamingPlatforms.map(p=>{const accounts=streamingAccounts.filter(a=>Number(a.platform_id)===Number(p.id)),subs=streamingSubscriptions.filter(s=>Number(s.platform_id)===Number(p.id)&&streamingDerivedStatus(s)==="active");return `<article class="streaming-row"><div class="streaming-row-main"><div class="streaming-row-title"><b>${streamingEsc(p.name)}</b>${p.active?'<span class="streaming-badge good">Activa</span>':'<span class="streaming-badge muted">Inactiva</span>'}</div><div class="streaming-row-meta"><span>${p.default_duration_days} días por defecto</span><span>${accounts.length} cuenta${accounts.length===1?"":"s"}</span><span>${subs.length} suscripción${subs.length===1?"":"es"} activa${subs.length===1?"":"s"}</span></div></div><div class="streaming-row-actions"><button class="ghost" onclick="streamingOpenPlatform(${p.id})">Editar</button></div></article>`}).join("")||'<div class="streaming-empty">Crea tu primera plataforma para comenzar.</div>'}
function renderStreamingRenewals(){const root=document.getElementById("streamingRenewalList");if(!root)return;root.innerHTML=streamingRenewals.map(r=>{const s=streamingSubscription(r.subscription_id),c=s?streamingCustomer(s.customer_id):null,p=s?streamingPlatform(s.platform_id):null;return `<article class="streaming-row"><div class="streaming-row-main"><div class="streaming-row-title"><b>${streamingEsc(c?.full_name||"Cliente")}</b><span class="streaming-badge good">Renovada</span></div><div class="streaming-row-meta"><span>▶ ${streamingEsc(p?.name||"Plataforma")}</span><span>${streamingDate(r.previous_expires_at)} → ${streamingDate(r.new_expires_at)}</span>${r.payment_method?`<span>${streamingEsc(r.payment_method)}</span>`:""}${Number(r.amount)>0?`<span>${streamingMoney(r.amount,r.currency_code)}</span>`:""}</div><small class="mut">${streamingDate(r.created_at,true)}${r.notes?` · ${streamingEsc(r.notes)}`:""}</small></div></article>`}).join("")||'<div class="streaming-empty">Las renovaciones aparecerán aquí automáticamente.</div>'}

function streamingOpenCustomer(id=null){if(!streamingWritable())return;const c=id?streamingCustomer(id):null;streamingShowModal(c?"Editar cliente":"Nuevo cliente",`<input id="streamingCustomerId" type="hidden" value="${c?.id||""}"><label>Nombre completo<input id="streamingCustomerName" value="${streamingEsc(c?.full_name||"")}" autocomplete="off"></label><div class="two"><label>WhatsApp / teléfono<input id="streamingCustomerPhone" value="${streamingEsc(c?.phone||"")}" inputmode="tel"></label><label>Correo<input id="streamingCustomerEmail" type="email" value="${streamingEsc(c?.email||"")}"></label></div><label>Notas<textarea id="streamingCustomerNotes">${streamingEsc(c?.notes||"")}</textarea></label><label class="streaming-check"><input id="streamingCustomerActive" type="checkbox" ${c?.active===false?"":"checked"}> Cliente activo</label>`,saveStreamingCustomer)}
async function saveStreamingCustomer(){const id=Number(document.getElementById("streamingCustomerId")?.value)||null,name=document.getElementById("streamingCustomerName")?.value.trim();if(!name)return streamingToast("Escribe el nombre del cliente");const row={restaurant_id:currentRestaurant,full_name:name,phone:document.getElementById("streamingCustomerPhone")?.value.trim()||"",email:document.getElementById("streamingCustomerEmail")?.value.trim()||null,notes:document.getElementById("streamingCustomerNotes")?.value.trim()||"",active:!!document.getElementById("streamingCustomerActive")?.checked,updated_at:new Date().toISOString()};const q=id?sb.from("streaming_customers").update(row).eq("id",id).eq("restaurant_id",currentRestaurant):sb.from("streaming_customers").insert(row);const {error}=await q;if(error)return streamingToast(error.message);streamingCloseModal();await streamingFetchAll();renderStreamingCustomers();renderStreamingSubscriptions();streamingToast("Cliente guardado")}

function streamingOpenPlatform(id=null){if(!streamingWritable())return;const p=id?streamingPlatform(id):null;streamingShowModal(p?"Editar plataforma":"Nueva plataforma",`<input id="streamingPlatformId" type="hidden" value="${p?.id||""}"><label>Nombre de plataforma<input id="streamingPlatformName" value="${streamingEsc(p?.name||"")}" placeholder="Netflix, Disney+, Spotify..."></label><label>Duración predeterminada (días)<input id="streamingPlatformDays" type="number" min="1" max="3650" value="${p?.default_duration_days||30}"></label><label class="streaming-check"><input id="streamingPlatformActive" type="checkbox" ${p?.active===false?"":"checked"}> Plataforma activa</label>`,saveStreamingPlatform)}
async function saveStreamingPlatform(){const id=Number(document.getElementById("streamingPlatformId")?.value)||null,name=document.getElementById("streamingPlatformName")?.value.trim(),days=Number(document.getElementById("streamingPlatformDays")?.value||30);if(!name)return streamingToast("Escribe el nombre de la plataforma");const row={restaurant_id:currentRestaurant,name,default_duration_days:days,active:!!document.getElementById("streamingPlatformActive")?.checked,updated_at:new Date().toISOString()};const q=id?sb.from("streaming_platforms").update(row).eq("id",id).eq("restaurant_id",currentRestaurant):sb.from("streaming_platforms").insert(row);const {error}=await q;if(error)return streamingToast(error.message);streamingCloseModal();await streamingFetchAll();renderStreamingPlatforms();streamingToast("Plataforma guardada")}

function streamingPlatformOptions(selected){return streamingPlatforms.filter(p=>p.active||Number(p.id)===Number(selected)).map(p=>`<option value="${p.id}" ${Number(p.id)===Number(selected)?"selected":""}>${streamingEsc(p.name)}</option>`).join("")}
function streamingCustomerOptions(selected){return streamingCustomers.filter(c=>c.active||Number(c.id)===Number(selected)).map(c=>`<option value="${c.id}" ${Number(c.id)===Number(selected)?"selected":""}>${streamingEsc(c.full_name)}${c.phone?` · ${streamingEsc(c.phone)}`:""}</option>`).join("")}
function streamingAccountOptions(platformId,selected){return `<option value="">Sin cuenta asignada</option>`+streamingAccounts.filter(a=>(a.active||Number(a.id)===Number(selected))&&(!platformId||Number(a.platform_id)===Number(platformId))).map(a=>{const free=Math.max(0,Number(a.max_slots||1)-streamingAccountUsed(a.id));return `<option value="${a.id}" ${Number(a.id)===Number(selected)?"selected":""}>${streamingEsc(a.label)} · ${free}/${a.max_slots} libres</option>`}).join("")}
function streamingSyncAccountOptions(selected=null){const platformId=Number(document.getElementById("streamingSubPlatform")?.value)||null,sel=document.getElementById("streamingSubAccount");if(sel)sel.innerHTML=streamingAccountOptions(platformId,selected);const p=streamingPlatform(platformId),days=document.getElementById("streamingSubDays");if(days&&p&&!days.dataset.touched)days.value=p.default_duration_days||30}

function streamingOpenAccount(id=null){if(!streamingWritable())return;if(!streamingPlatforms.length)return streamingToast("Primero crea una plataforma");const a=id?streamingAccount(id):null;streamingShowModal(a?"Editar cuenta / cupos":"Nueva cuenta / cupos",`<input id="streamingAccountId" type="hidden" value="${a?.id||""}"><label>Plataforma<select id="streamingAccountPlatform">${streamingPlatformOptions(a?.platform_id)}</select></label><label>Nombre interno de la cuenta<input id="streamingAccountLabel" value="${streamingEsc(a?.label||"")}" placeholder="Netflix Familiar 1"></label><label>Identificador / correo de acceso<input id="streamingAccountLogin" value="${streamingEsc(a?.login_identifier||"")}" placeholder="cuenta@email.com"><small class="mut">Por seguridad no guardamos contraseñas de servicios de streaming.</small></label><label>Cupos / perfiles disponibles<input id="streamingAccountSlots" type="number" min="1" max="100" value="${a?.max_slots||1}"></label><label>Notas<textarea id="streamingAccountNotes">${streamingEsc(a?.notes||"")}</textarea></label><label class="streaming-check"><input id="streamingAccountActive" type="checkbox" ${a?.active===false?"":"checked"}> Cuenta activa</label>`,saveStreamingAccount)}
async function saveStreamingAccount(){const id=Number(document.getElementById("streamingAccountId")?.value)||null,platform_id=Number(document.getElementById("streamingAccountPlatform")?.value),label=document.getElementById("streamingAccountLabel")?.value.trim(),max_slots=Number(document.getElementById("streamingAccountSlots")?.value||1);if(!platform_id||!label)return streamingToast("Selecciona plataforma y escribe un nombre para la cuenta");const row={restaurant_id:currentRestaurant,platform_id,label,login_identifier:document.getElementById("streamingAccountLogin")?.value.trim()||"",max_slots,notes:document.getElementById("streamingAccountNotes")?.value.trim()||"",active:!!document.getElementById("streamingAccountActive")?.checked,updated_at:new Date().toISOString()};const q=id?sb.from("streaming_accounts").update(row).eq("id",id).eq("restaurant_id",currentRestaurant):sb.from("streaming_accounts").insert(row);const {error}=await q;if(error)return streamingToast(error.message);streamingCloseModal();await streamingFetchAll();renderStreamingAccounts();renderStreamingPlatforms();streamingToast("Cuenta guardada")}

function streamingOpenSubscription(id=null,customerPreset=null){if(!streamingWritable())return;if(!streamingCustomers.length)return streamingToast("Primero registra un cliente");if(!streamingPlatforms.length)return streamingToast("Primero crea una plataforma");const s=id?streamingSubscription(id):null,start=s?.starts_at||new Date().toISOString(),duration=s?Math.max(1,Math.round((new Date(s.expires_at)-new Date(s.starts_at))/86400000)):30;streamingShowModal(s?"Editar suscripción":"Nueva suscripción",`<input id="streamingSubId" type="hidden" value="${s?.id||""}"><label>Cliente<select id="streamingSubCustomer">${streamingCustomerOptions(s?.customer_id||customerPreset)}</select></label><label>Plataforma<select id="streamingSubPlatform" onchange="document.getElementById('streamingSubDays').dataset.touched='';streamingSyncAccountOptions()">${streamingPlatformOptions(s?.platform_id||streamingPlatforms[0]?.id)}</select></label><label>Cuenta / cupo<select id="streamingSubAccount"></select></label><div class="two"><label>Inicio<input id="streamingSubStart" type="datetime-local" value="${streamingDateInput(start)}"></label><label>Duración (días)<input id="streamingSubDays" type="number" min="1" max="3650" value="${duration}" oninput="this.dataset.touched='1'"></label></div><div class="two"><label>Perfil / cupo<input id="streamingSubProfile" value="${streamingEsc(s?.profile_label||"")}" placeholder="Perfil 2"></label><label>Precio cobrado<input id="streamingSubPrice" type="number" min="0" step="1" value="${Number(s?.price||0)}"></label></div><label>Estado<select id="streamingSubStatus"><option value="active" ${!s||s.status==="active"?"selected":""}>Activa</option><option value="paused" ${s?.status==="paused"?"selected":""}>Pausada</option><option value="cancelled" ${s?.status==="cancelled"?"selected":""}>Cancelada</option></select></label><label class="streaming-check"><input id="streamingSubAutoRenew" type="checkbox" ${s?.auto_renew?"checked":""}> Marcar para renovación automática / recordatorio</label><label>Notas<textarea id="streamingSubNotes">${streamingEsc(s?.notes||"")}</textarea></label>`,saveStreamingSubscription);requestAnimationFrame(()=>streamingSyncAccountOptions(s?.account_id))}
async function saveStreamingSubscription(){const id=Number(document.getElementById("streamingSubId")?.value)||null,customer_id=Number(document.getElementById("streamingSubCustomer")?.value),platform_id=Number(document.getElementById("streamingSubPlatform")?.value),account_id=Number(document.getElementById("streamingSubAccount")?.value)||null,startRaw=document.getElementById("streamingSubStart")?.value,days=Number(document.getElementById("streamingSubDays")?.value||30);if(!customer_id||!platform_id||!startRaw||days<1)return streamingToast("Completa cliente, plataforma, inicio y duración");const starts_at=new Date(startRaw).toISOString(),expires_at=new Date(new Date(startRaw).getTime()+days*86400000).toISOString();const row={restaurant_id:currentRestaurant,customer_id,platform_id,account_id,profile_label:document.getElementById("streamingSubProfile")?.value.trim()||"",starts_at,expires_at,status:document.getElementById("streamingSubStatus")?.value||"active",price:Number(document.getElementById("streamingSubPrice")?.value||0),currency_code:streamingCurrency(),auto_renew:!!document.getElementById("streamingSubAutoRenew")?.checked,notes:document.getElementById("streamingSubNotes")?.value.trim()||"",updated_at:new Date().toISOString()};const q=id?sb.from("streaming_subscriptions").update(row).eq("id",id).eq("restaurant_id",currentRestaurant):sb.from("streaming_subscriptions").insert(row);const {error}=await q;if(error)return streamingToast(error.message);streamingCloseModal();await streamingFetchAll();renderStreamingSubscriptions();renderStreamingAccounts();streamingToast("Suscripción guardada")}

function streamingOpenRenewal(id){if(!streamingWritable())return;const s=streamingSubscription(id);if(!s)return;const c=streamingCustomer(s.customer_id),p=streamingPlatform(s.platform_id),days=p?.default_duration_days||30;streamingShowModal("Renovar suscripción",`<input id="streamingRenewSubId" type="hidden" value="${s.id}"><div class="streaming-renew-summary"><b>${streamingEsc(c?.full_name||"Cliente")}</b><span>${streamingEsc(p?.name||"Plataforma")}</span><span>Vence: ${streamingDate(s.expires_at)}</span></div><label>Extender por días<input id="streamingRenewDays" type="number" min="1" max="3650" value="${days}"></label><div class="two"><label>Monto cobrado<input id="streamingRenewAmount" type="number" min="0" step="1" value="${Number(s.price||0)}"></label><label>Forma de pago<input id="streamingRenewMethod" placeholder="Efectivo, transferencia..."></label></div><label>Notas<textarea id="streamingRenewNotes"></textarea></label>`,saveStreamingRenewal)}
async function saveStreamingRenewal(){const p_subscription_id=Number(document.getElementById("streamingRenewSubId")?.value),p_days=Number(document.getElementById("streamingRenewDays")?.value||0),p_amount=Number(document.getElementById("streamingRenewAmount")?.value||0),p_payment_method=document.getElementById("streamingRenewMethod")?.value.trim()||"",p_notes=document.getElementById("streamingRenewNotes")?.value.trim()||"";const {error}=await sb.rpc("streaming_renew_subscription",{p_subscription_id,p_days,p_amount,p_payment_method,p_notes});if(error)return streamingToast(error.message);streamingCloseModal();await streamingFetchAll();renderStreamingSubscriptions();renderStreamingRenewals();renderStreamingAccounts();streamingToast("Suscripción renovada")}

function streamingPhoneUrl(phone,text){const digits=String(phone||"").replace(/\D/g,"");return digits?`https://wa.me/${digits}?text=${encodeURIComponent(text)}`:""}
function streamingOpenWhatsApp(id){const s=streamingSubscription(id),c=s&&streamingCustomer(s.customer_id),p=s&&streamingPlatform(s.platform_id);if(!c?.phone)return streamingToast("Este cliente no tiene WhatsApp registrado");const days=streamingDaysLeft(s.expires_at),when=days<0?`venció el ${streamingDate(s.expires_at)}`:days===0?"vence hoy":`vence el ${streamingDate(s.expires_at)}`;window.open(streamingPhoneUrl(c.phone,`Hola ${c.full_name}, tu suscripción de ${p?.name||"streaming"} ${when}. Escríbeme para renovarla.`),"_blank","noopener")}
function streamingCustomerWhatsApp(id){const c=streamingCustomer(id);if(!c?.phone)return;window.open(streamingPhoneUrl(c.phone,`Hola ${c.full_name}, te escribo por tu servicio de streaming.`),"_blank","noopener")}

function streamingSetMetric(id,label,value,small){const strong=document.getElementById(id);if(!strong)return;strong.textContent=value;const box=strong.parentElement;if(box){const span=box.querySelector("span");const sm=box.querySelector("small");if(span)span.textContent=label;if(sm)sm.textContent=small||""}}
function renderStreamingDashboard(){
 const active=streamingSubscriptions.filter(s=>streamingDerivedStatus(s)==="active"),expiring=active.filter(s=>{const d=streamingDaysLeft(s.expires_at);return d!=null&&d>=0&&d<=7}),customers=streamingCustomers.filter(c=>c.active).length,free=streamingFreeSlots();
 streamingSetMetric("statSalesToday","Suscripciones activas",active.length,"Accesos vigentes");streamingSetMetric("statOrdersToday","Vencen en 7 días",expiring.length,"Requieren seguimiento");streamingSetMetric("statProducts","Clientes activos",customers,"Directorio actual");streamingSetMetric("statAverage","Cupos libres",free,"Disponibles ahora");
 const salesTitle=document.querySelector(".dashboard-detail-sales h2");if(salesTitle)salesTitle.textContent="Renovaciones recientes";const salesDesc=document.querySelector(".dashboard-detail-sales .mut");if(salesDesc)salesDesc.textContent="Actividad de renovaciones de los últimos días.";
 const sales=document.getElementById("salesChart");if(sales){const seven=Array.from({length:7},(_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(6-i));const next=new Date(d);next.setDate(next.getDate()+1);return {d,count:streamingRenewals.filter(r=>{const t=new Date(r.created_at);return t>=d&&t<next}).length}});sales.innerHTML='<div class="streaming-mini-chart">'+seven.map(x=>`<div><i style="height:${Math.max(6,Math.min(70,x.count*18+6))}px"></i><b>${x.count}</b><span>${x.d.toLocaleDateString(streamingLocale(),{weekday:"short"})}</span></div>`).join("")+'</div>'}
 const status=document.getElementById("statusChart");if(status){const expired=streamingSubscriptions.filter(s=>streamingDerivedStatus(s)==="expired").length;status.innerHTML=`<div class="item"><b>Activas</b><span class="pill">${active.length}</span></div><div class="item"><b>Por vencer ≤ 7 días</b><span class="pill">${expiring.length}</span></div><div class="item"><b>Vencidas</b><span class="pill">${expired}</span></div>`}
 const top=document.getElementById("topProducts");if(top){const usage=streamingPlatforms.map(p=>({name:p.name,count:active.filter(s=>Number(s.platform_id)===Number(p.id)).length})).sort((a,b)=>b.count-a.count).slice(0,8);top.innerHTML=usage.map((x,i)=>`<div class="item"><b>${i+1}. ${streamingEsc(x.name)}</b><span class="pill">${x.count} activa${x.count===1?"":"s"}</span></div>`).join("")||'<p class="mut">Sin suscripciones todavía.</p>'}
 const stockTitle=document.querySelector(".dashboard-detail-stock h2");if(stockTitle)stockTitle.textContent="Plataformas más utilizadas";
 const stockDesc=document.querySelector(".dashboard-detail-stock .mut");if(stockDesc)stockDesc.textContent="Ranking por suscripciones activas.";
 const statusTitle=document.querySelector(".dashboard-detail-orders h2");if(statusTitle)statusTitle.textContent="Estado de suscripciones";
 document.querySelectorAll(".system-status-list b").forEach((b,i)=>b.textContent=["Clientes y suscripciones","Cuentas y cupos","Vencimientos y renovaciones"][i]||b.textContent);
 document.querySelectorAll(".system-status-list small").forEach((b,i)=>b.textContent=["Datos separados por negocio","Capacidad controlada automáticamente","Historial y alertas disponibles"][i]||b.textContent);
}
async function refreshStreamingDashboard(){try{await streamingFetchAll();renderStreamingDashboard()}catch(e){console.error(e);streamingToast(e.message||"No se pudo cargar el resumen de Streaming")}}
